### ISSUE TITLE
Create UPM package

### ISSUE THREAD

**Issue by MartinGonzalez** [amplitude/unity-plugin#43]
This will impact in how developers can integrate the plugin in their projects. It would be easier and we can keep track of the updates.

**Comment by MartinGonzalez** [comment]
Is there any new about this?

**Comment by haoliu-amp** [comment]
Hello, we haven't started working on this, but this is what we are up to.

**Comment by MartinGonzalez** [comment]
Hi, any news about this?

**Comment by JoNax97** [comment]
Hi! This would be very useful for us, too. It'd be great if you cold give an update!

**Comment by haoliu-amp** [comment]
Hello! This is in our backlog and we target to do it within next 1-2 months.

**Comment by Xeoneid** [comment]
Thanks for responding @haoliu-amp !

**Comment by dantetam** [comment]
Hello all, I'm currently working on this issue. Sorry for the delay.

To give you all updates, it is a little more complicated to create a UPM package and .asmdef files because of the architecture of our app, with the Android and iOS plugins and bridging code to these native libraries. 

We would like to listen to some customer insights. How would creating the UPM benefit you or your organization? Specifically, how many steps does this save you?

**Comment by dantetam** [comment]
Hello all,

We have completed this feature: the ability to download the Unity SDK through Git and have the Unity Package Manager automatically resolve by version. Extra instructions at [the Unity Amplitude developer docs](https://developers.amplitude.com/docs/unity). 

```
Ensure git is installed. In Unity, click Window > Package Manager. Click the plus + sign and select Add package from Git URL. Type in the URL 
https://github.com/amplitude/unity-plugin.git?path=/Assets, 
and then press Add. Wait for the Unity editor to import the project from Git.
```

**Comment by dantetam** [comment]
Thank you for the excellent suggestiong @MartinGonzalez 

For developers, see #64
