### ISSUE TITLE
User property prepend/preInsert/postInsert/remove are not supported

### ISSUE THREAD

**Issue by lebek** [amplitude/unity-plugin#69]
The Android and iOS SDKs both support user property `prepend`, `preInsert`, `postInsert`, and `remove`:

Android: https://developers.amplitude.com/docs/android#arrays-in-user-properties
iOS: https://developers.amplitude.com/docs/ios#arrays-in-user-properties

It would be great if we could support them in the Unity plugin as well.

**Comment by dantetam** [comment]
Hello @lebek ,

Thanks for calling this out. We just added these functions to Android. Makes sense for Unity. It's been added to the backlog. Targeting for next sprint 4/26 - 5/7.

**Comment by yuhao900914** [comment]
Hello @lebek ,
Thanks for your patient. We want to let you know the user property `prepend`, `preInsert`, `postInsert`, and `remove` functions are been supported in the latest unity-plugin [v2.2.0.](https://github.com/amplitude/unity-plugin/releases/tag/v2.2.0) 
I will close this feature request since it has been implemented.

**Comment by lebek** [comment]
Great news, thanks!
